// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOEZhghibQMArt29Z4R4vtFv4IxBbO9H8',
    appId: '1:688102645842:web:bc45489baff9abac433f8b',
    messagingSenderId: '688102645842',
    projectId: 'aban-sermon',
    authDomain: 'aban-sermon.firebaseapp.com',
    storageBucket: 'aban-sermon.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgf_Id-SK0NnsEP8N_e0cmgELBHbn9NlY',
    appId: '1:688102645842:ios:f4fd83753c060474433f8b',
    messagingSenderId: '688102645842',
    projectId: 'aban-sermon',
    storageBucket: 'aban-sermon.firebasestorage.app',
    iosBundleId: 'com.example.abansermon',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgf_Id-SK0NnsEP8N_e0cmgELBHbn9NlY',
    appId: '1:688102645842:ios:f4fd83753c060474433f8b',
    messagingSenderId: '688102645842',
    projectId: 'aban-sermon',
    storageBucket: 'aban-sermon.firebasestorage.app',
    iosBundleId: 'com.example.abansermon',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWpeYvFBuo9Q66-6Q2HRIQdd6sMz5Lrh4',
    appId: '1:688102645842:android:5149b49f8a16b803433f8b',
    messagingSenderId: '688102645842',
    projectId: 'aban-sermon',
    storageBucket: 'aban-sermon.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOEZhghibQMArt29Z4R4vtFv4IxBbO9H8',
    appId: '1:688102645842:web:41eebf99023b2df5433f8b',
    messagingSenderId: '688102645842',
    projectId: 'aban-sermon',
    authDomain: 'aban-sermon.firebaseapp.com',
    storageBucket: 'aban-sermon.firebasestorage.app',
  );

}